feat: add Pager styling
telerik/kendo-theme-material pull request #25
Opened 2018-01-10 12:30 UTC by theOrlin

2018-01-17 11:51 UTC, gyoshev commented on scss/pager/_theme.scss
> +        padding: $toolbar-padding-x / 2;
It appears that the theme file copies the styles from theme-default and adds layout fixes. I'd suggest introducing more variables to the pager layout in theme-default and using them instead, like `$pager-padding-x / $pager-padding-y`. This will allow the default theme to be reused, through its variables, reducing code debt and preventing errors (currently the `$pager-numbers-text` variable does nothing).

Alternatively, if you need specific changes to the layout, use the [approach shown in input/_layout](https://github.com/telerik/kendo-theme-material/blob/develop/scss/input/_layout.scss#L11).

2018-01-29 11:53 UTC, joneff requested changes

2018-01-29 11:53 UTC, joneff commented on scss/pager/_theme.scss
> +@include exports ('input/layout/pager/material') {
This must be placed in `pager/_layout.scss` and the name should be `pager/layout/material`

2018-02-09 12:20 UTC, gyoshev commented
PR moved to monorepo.

2018-02-09 12:20 UTC, closed without merging